version: '3'
services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "80:80"

  influx:
    image: influxdb:1.7

  #TODO add zookeeper
  #TODO add kafka
  #TODO add IsHome
  #TODO add Monitoring
  #TODO add AMQP server
  #TODO add Boodschappenlijstje
