version: '3'
services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"

  influx:
    image: influxdb:1.7
    environment:
      INFLUXDB_DB: grafzicht
    ports:
      - "8086:8086"
    volumes:
      - /data/influx:/var/lib/influxdb


  #TODO add zookeeper
  #TODO add kafka
  #TODO add IsHome
  #TODO add Monitoring
  #TODO add AMQP server
  #TODO add Boodschappenlijstje
