version: '3'
services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - grafana

  influx:
    image: influxdb:1.7
    container_name: influx
    environment:
      INFLUXDB_DB: grafzicht
    ports:
      - "8086:8086"
    volumes:
      - /data/influx:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_INSTALL_PLUGINS: andig-darksky-datasource,citilogics-geoloop-panel,farski-blendstat-panel,fatcloud-windrose-panel,grafana-clock-panel,grafana-worldmap-panel,jdbranham-diagram-panel,natel-plotly-panel,neocat-cal-heatmap-panel,petrslavotinek-carpetplot-panel,ryantxu-ajax-panel,snuids-radar-panel
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_SERVER_ROOT_URL: http://grafzicht.nl/grafana/
    volumes:
      - /data/grafana/data:/var/lib/grafana
    depends_on:
      - influx

  pihole:
    image: pihole/pihole
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Amsterdam'
      WEBPASSWORD: 'H3Awl7yd'
      DNS1: '9.9.9.9'
      DNS2: 'no'
    volumes:
      - /data/pihole/pihole/:/etc/pihole/
      - /data/pihole/dnsmasq/:/etc/dnsmasq.d/



  #TODO add zookeeper
  #TODO add kafka
  #TODO add IsHome
  #TODO add Monitoring
  #TODO add AMQP server
  #TODO add Boodschappenlijstje
