version: '3'
services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"

  raint-server:
    build: ./raint/server
    ports:
      - "8080:8080"

  #TODO add raint-overview
  #TODO add zookeeper
  #TODO add kafka
  #TODO add IsHome
  #TODO add Monitoring
  #TODO add AMQP server
  #TODO add Boodschappenlijstje
